import { LOSS_MARGIN_PRESETS, ORDER_ROUNDING_PRESETS } from '../models/Order';

export const DEFAULT_LOSS_MARGIN_PERCENT = 5;
export const DEFAULT_PANEL_LOSS_MARGIN_PERCENT = 10;

export { LOSS_MARGIN_PRESETS, ORDER_ROUNDING_PRESETS };
